// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthorizedAPI = "authorized_api"

// AuthorizedAPI mapped from table <authorized_api>
type AuthorizedAPI struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	BusinessKey string    `gorm:"column:business_key;not null" json:"business_key"`                       // 调用方key
	Method      string    `gorm:"column:method;not null" json:"method"`                                   // 请求方式
	API         string    `gorm:"column:api;not null" json:"api"`                                         // 请求地址
	IsDeleted   bool      `gorm:"column:is_deleted;not null;default:-1" json:"is_deleted"`                // 是否删除 1:是  -1:否
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	CreatedUser string    `gorm:"column:created_user;not null" json:"created_user"`                       // 创建人
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	UpdatedUser string    `gorm:"column:updated_user;not null" json:"updated_user"`                       // 更新人
}

// TableName AuthorizedAPI's table name
func (*AuthorizedAPI) TableName() string {
	return TableNameAuthorizedAPI
}
