
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.read]
    addr = "127.0.0.1:3306"
    name = "lida_gin_api"
    pass = "password"
    user = "root222"
    connMaxLifeTime = 60
    maxIdleConn = 60
    maxOpenConn = 10

  [mysql.write]
    addr = "127.0.0.1:3306"
    name = "lida_gin_api"
    pass = "password"
    user = "root333"
    connMaxLifeTime = 60
    maxIdleConn = 60
    maxOpenConn = 10

[redis]
  addr = "127.0.0.1:6379"
  db = "0"
  maxretries = 3
  minidleconns = 5
  pass = ""
  poolsize = 10
